export enum Tags {
  WINTER='WINTER',
  SUMMER='SUMMER',
  FALL='FALL',
  SPRING='SPRING',
  TANK_SHIRT='TANK_SHIRT',
  T_SHIRT='T_SHIRT',
  LONG_SLEEVE_SHIRT='LONG_SLEEVE_SHIRT',
  SHORT_PANTS='SHORT_PANTS',
  LONG_PANTS='LONG_PANTS',
  JEANS='JEANS'
}

